language: node_js

install:
  - npm install
  
node_js:
  - 0.10
  
script:
  - gulp dist 
  
notifications:
  slack: sapuxddub:80SUMiwMrkrzS9vFX1l4kZGw
  
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
